name: lightcast_camera
description: LightCast Pastor/Crowd camera Android application.
publish_to: "none"
version: 0.1.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^1.6.1
  flutter_riverpod: ^2.5.1
  lightcast_shared:
    path: ../../packages/lightcast_shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
