name: lightcast_camera
description: LightCast Pastor/Crowd camera Android application.
publish_to: "none"
version: 0.1.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.11.6 # Downgraded to stable version to fix SDK 36 compile error
  flutter_riverpod: ^2.5.1
  web_socket_channel: ^2.4.0  # ← ADD THIS LINE
  lightcast_shared:
    path: ../../packages/lightcast_shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
