name: lightcast_director
description: LightCast Director Android application.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: 0.11.6
  flutter_riverpod: 2.5.1
  lightcast_shared:
    path: ../../packages/lightcast_shared
  shelf: 1.4.1
  shelf_web_socket: 1.0.4
  web_socket_channel: 2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0

flutter:
  uses-material-design: true
  
  # This section tells Flutter to include your images folder
  assets:
    - assets/images/
